version: '3.8'
services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    restart: always
    ports:
      - '3003:3000'
    depends_on:
      - nest-postgres

  nest-postgres:
    image: postgres:14
    container_name: nest-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - nest-postgres:/var/lib/postgresql/data
      - ./prisma/create-db-user.sql:/docker-entrypoint-initdb.d/create-db-user.sql

volumes:
  nest-postgres:
    name: callgent-postgres-db
