import $RefParser from '@apidevtools/json-schema-ref-parser';
import {
  BadRequestException,
  NotFoundException,
  NotImplementedException,
} from '@nestjs/common';
import {
  ParameterObject,
  RequestBodyObject,
  SchemaObject,
  SecurityRequirementObject,
  SecuritySchemeObject,
  ServerObject,
} from '@nestjs/swagger/dist/interfaces/open-api-spec.interface';
import postmanToOpenApi from '@pond918/postman-to-openapi';
import { EntryType, Prisma } from '@prisma/client';
import { Liquid } from 'liquidjs';
import yaml from 'yaml';
import { AgentsService } from '../../agents/agents.service';
import { EndpointDto } from '../../endpoints/dto/endpoint.dto';
import { ServiceResponse } from '../../event-listeners/event-object';
import { EntryDto } from '../dto/entry.dto';
import {
  ClientRequestEvent,
  InvokeStatus,
} from '../events/client-request.event';

abstract class AbstractEntryAdaptor {
  constructor(protected readonly agentsService: AgentsService) {}

  /** entry lifecycle */
  preCreate(data: Prisma.EntryUncheckedCreateInput) {
    if (!data.host) throw new BadRequestException('host is required');
    data.host = data.host.replace('{id}', data.id);
    // init entry name
    data.name || (data.name = data.host);
  }

  /** Entry config. */
  // abstract getConfig(): EntryConfig;

  /** get callback param */
  abstract getCallback(callback: string, reqEntry?: EntryDto): Promise<string>;

  /** send response back to client */
  abstract callback(resp: any): Promise<boolean>;
}

interface _ClientEntryAdaptor {
  /** client host is auto generated by adaptor */
  _genClientHost(entry: Prisma.EntryUncheckedCreateInput);
  initClient(initParams: object, entry: EntryDto): Promise<string>;

  /** preprocess request, replace raw request */
  preprocess(reqEvent: ClientRequestEvent, entry: EntryDto): Promise<void>;
}

/** result pending, or response data */
export class PendingOrResponse {
  statusCode?: 2;
  message?: string;
  data?: ServiceResponse;
}

export abstract class ServerEntryAdaptor extends AbstractEntryAdaptor {
  protected readonly templateEngine: Liquid;
  constructor(protected readonly agentsService: AgentsService) {
    super(agentsService);
    this.templateEngine = new Liquid({ keepOutputType: true });
  }

  abstract isAsync(endpoint: EndpointDto): boolean;

  /** init the entry. result in generated content */
  abstract initServer(initParams: object, entry: EntryDto): Promise<string>;

  /**
   * request lifecycle.
   * invoke server, returns pending or real response
   * @param sentry config
   * @param reqEvent context
   */
  async invoke(
    fun: EndpointDto,
    args: { [key: string]: any },
    sentry: EntryDto,
    reqEvent: ClientRequestEvent,
    ctx: InvokeStatus,
  ): Promise<{
    statusCode?: 2;
    message?: string;
    data?: any;
  }> {
    if (!args) args = {};
    this._mergeDefaultValues(fun, args);
    return this._invoke(fun, args, sentry, reqEvent, ctx);
  }

  /**
   * merge default args:
   * - eval arg name/value template
   * - fill default value, including merge array/object undefined props
   * @param args must not empty
   */
  protected _mergeDefaultValues(
    fun: EndpointDto,
    args: { [key: string]: any },
  ) {
    const { parameters, requestBody } =
      (fun.params as unknown as {
        parameters: ParameterObject[];
        requestBody: RequestBodyObject;
      }) || {};
    if (!parameters?.length && !requestBody) return;

    // add request body as param
    const params = parameters ? [...parameters] : [];
    const schemas = requestBody?.content && Object.values(requestBody.content);
    if (schemas?.length) {
      if (schemas.length > 1)
        throw new NotImplementedException('multiple content type');
      params.push({
        name: 'requestBody',
        schema: schemas[0].schema,
        in: 'body',
      } as any);
    }

    // merge default values
    for (const p of params) {
      this._mergeSchemaDefaultValue(
        p as { name: string; schema: SchemaObject },
        args,
        args,
      );
    }
  }

  /**
   * merge default values into args if not set, e.g.:
   * - { name:'requestBody', schema: { properties: { messages: [LLMMessage], 'messages.0': { default: '{{}}' } } } }
   *   - default value will be merged into messages=[undefined, 1,2], as messages[0] is undefined
   * - { name:'requestBody', schema: { "type": "array" } }
   * - { name:'requestBody.0', schema: { "type": "array" } }
   *
   * - if any prop is undefined, default value is applied
   * - if any prop is not empty, try merge nested undefined props
   * - null is treat as set, and no nested merge
   * - if arg is empty, no merge
   * - array is deeply flattened, and item count not changed
   *
   * @param p p.name may be template and path, e.g. 'requestBody.{{ index }}'
   * @param arg current parameter value
   */
  protected _mergeSchemaDefaultValue(
    { name, schema }: { name: string; schema: SchemaObject },
    ctx: { [key: string]: any },
    arg: any,
  ): void {
    // if arg empty or no def and nested def, no merge
    if (!arg || !schema) return;

    // eval name template to path
    const names = this._templateEval(name, ctx, arg).split('.');
    let val = this._getValue(arg, names); // value to merge

    //// treat all as array
    // if val is array, flatten all items and switch schema to item
    const isArrayValue = schema.items || schema.type === 'array';
    let flatArray: any[];
    if (isArrayValue) {
      // if array length, means no item to merge
      flatArray = val?.flat(100);
      if (!flatArray?.length) return;
      do {
        schema = schema.items as SchemaObject; // flatten arrays
      } while (schema.items || schema.type === 'array');
      if (!schema) return; // no def nor nested def to merge
    } else flatArray = [val];

    //// replace undefined value with default
    if (
      schema.default !== undefined &&
      flatArray.some((v) => v === undefined)
    ) {
      const defValue = this._templateEval(schema.default, ctx, arg);
      if (defValue !== undefined) {
        if (isArrayValue) this._setValueTraverse(val, defValue);
        else this._setValue(arg, names, defValue);
      }
    }

    //// merge item nested props
    flatArray.forEach((v, i) => {
      if (!v || !schema.properties) return; // no nested props to merge

      //// merge nested props
      for (const [name, propSchema] of Object.entries(schema.properties)) {
        this._mergeSchemaDefaultValue(
          { schema: propSchema as SchemaObject, name },
          ctx,
          v,
        );
      }
    });
  }

  /** traverse deep array, replace all undefined item with v */
  private _setValueTraverse(arr: any[], v: any) {
    for (let i = 0; i < arr.length; i++) {
      const item = arr[i];
      if (item === undefined) arr[i] = v;
      else if (Array.isArray(item)) this._setValueTraverse(item, v);
    }
  }

  /**
   * null safe set: if middle value empty, init it. name: a.b
   * @returns new obj if obj is undefined or null, else obj
   */
  private _setValue(obj: object, name: string, defVal: any) {
    const ns = name.split('.');
    const o = ns.length > 1 ? this._getValue(obj, ns.slice(0, -1)) : obj;
    o[ns[ns.length - 1]] = defVal;
    return obj;
  }

  /** null safe get. name: a.b */
  private _getValue(args: { [key: string]: any }, name: string | string[]) {
    const names = Array.isArray(name) ? name : name.split('.');
    let v: any = args;
    for (const n of names) {
      // return if undefined or null
      if (v === undefined || v === null) return v;
      v = v[n];
    }
    return v;
  }

  /**
   * @param value if string, eval it as template; if object/array, eval every prop
   * @param ctx
   * @param _ current value
   * @returns evaluated value keeping same type as vars, e.g. '{{age}}' -> 10
   */
  protected _templateEval(value: any, ctx: { [key: string]: any }, _?: any) {
    if (typeof value === 'string') return this._templateEvalStr(value, ctx, _);
    if (!value || typeof value !== 'object') return value;
    if (Array.isArray(value))
      return value.map((v) => this._templateEval(v, ctx, _));

    value = { ...value };
    for (const [k, v] of Object.entries(value))
      value[k] = this._templateEval(v, ctx, _);
    return value;
  }

  /**
   * @returns evaluated value keeping same type as vars, e.g. '{{age}}' -> 10
   */
  private _templateEvalStr(tpl: string, ctx: { [key: string]: any }, _?: any) {
    if (tpl.indexOf('{') < 0) return tpl;
    try {
      return this.templateEngine.parseAndRenderSync(tpl, { ...ctx, _ });
    } catch (e) {
      throw new BadRequestException(e.message);
    }
  }

  /** request lifecycle */
  protected abstract _invoke(
    fun: EndpointDto,
    args: { [key: string]: any },
    sentry: EntryDto,
    reqEvent: ClientRequestEvent,
    ctx: InvokeStatus,
  ): Promise<{
    statusCode?: 2;
    message?: string;
    data?: any;
  }>;

  /** request lifecycle: postprocess response */
  abstract postprocess(
    resp: any,
    reqEvent: ClientRequestEvent,
    fun: EndpointDto,
    ctx: InvokeStatus,
  ): Promise<ServiceResponse>;

  /**
   * sep lifecycle, parse APIs to openAPI.json format
   * @see https://github.com/OAI/OpenAPI-Specification/blob/main/schemas/v3.0/schema.json
   */
  async parseApis({
    text,
    format,
  }: {
    text: string;
    format?: 'json' | 'yaml' | 'text';
  }) {
    const ret: ApiSpec = { apis: [] };

    let json: any;
    try {
      if (
        (!format || format == 'json') &&
        text.startsWith('{') &&
        text.indexOf('https://schema.getpostman.com/json/collection') > 0
      ) {
        // convert postman collection to openAPI.JSON
        text = await postmanToOpenApi(text, null, {
          outputFormat: 'json',
          itemServers: true,
          replaceVars: true,
        });
        format = 'json';
      }

      if (format == 'json') {
        json = JSON.parse(text);
      } else if (format == 'yaml') {
        json = yaml.parse(text);
      } else {
        try {
          json = JSON.parse(text);
        } catch (err) {
          try {
            json = yaml.parse(text);
          } catch (err) {
            // pass
          }
        }
      }

      if (!json?.openapi || !json.paths) {
        // convert text to openAPI.JSON
        throw new Error('TODO: Not implemented.');
      }
    } catch (err) {
      throw new BadRequestException(
        `Failed to parse content as ${format || 'text'} format, msg: ${
          err.message
        }`,
      );
    }
    try {
      json = await $RefParser.dereference(json);
    } catch (err) {
      throw new BadRequestException(
        'Invalid openAPI.JSON, failed to dereference, ' + err.message,
      );
    }
    const { openapi, paths, components, security, servers } = json; // TODO: save components onto SEP
    if (!openapi?.startsWith('3.0'))
      throw new BadRequestException(
        'Only openAPI `3.0.x` is supported now, openapi=' + openapi,
      );
    ret.securitySchemes = components?.securitySchemes;
    ret.servers = servers;
    ret.securities = security;

    const ps = paths && Object.entries(paths);
    if (ps?.length) {
      for (const [path, pathApis] of ps) {
        const entries = Object.entries(pathApis);
        for (const [method, restApi] of entries) {
          const operationId = restApi.operationId;
          const summary = restApi.summary || '';
          const description = `${restApi.description || ''}${restApi.description && restApi.tags?.length ? '; ' : ''}${restApi.tags?.length ? 'Tags: ' + restApi.tags.join(', ') : ''}`;
          const responses = restApi.responses;
          const params = {
            parameters: restApi.parameters,
            requestBody: restApi.requestBody,
          };
          const securities = restApi.security;
          const servers = restApi.servers;

          // TODO restApi.callbacks

          ret.apis.push({
            path,
            operationId,
            method: method.toUpperCase(),
            summary,
            description,
            securities,
            servers,
            params,
            responses,
            rawJson: restApi,
          });
        }
      }
      return ret;
    }
    throw new NotFoundException('No API found in the text.');
  }
}

export abstract class ClientEntryAdaptor
  extends AbstractEntryAdaptor
  implements _ClientEntryAdaptor
{
  /** entry init */
  preCreate(data: Prisma.EntryUncheckedCreateInput): void {
    this._genClientHost(data);
    super.preCreate(data);
  }

  /** entry init */
  abstract _genClientHost(entry: Prisma.EntryUncheckedCreateInput);
  /** entry init */
  abstract initClient(initParams: object, entry: EntryDto): Promise<string>;
  /** request lifecycle */
  abstract preprocess(
    reqEvent: ClientRequestEvent,
    entry: EntryDto,
  ): Promise<void>;
  /** cep lifecycle */
}

export abstract class BothEntryAdaptor
  extends ServerEntryAdaptor
  implements _ClientEntryAdaptor
{
  preCreate(data: Prisma.EntryUncheckedCreateInput): void {
    // gen client host to be called
    if (data.type !== EntryType.SERVER) this._genClientHost(data);
    super.preCreate(data);
  }

  abstract _genClientHost(entry: Prisma.EntryUncheckedCreateInput);
  abstract initClient(initParams: object, entry: EntryDto): Promise<string>;
  abstract preprocess(
    reqEvent: ClientRequestEvent,
    entry: EntryDto,
  ): Promise<void>;
}

export class ApiSpec {
  apis: {
    operationId: string;
    path: string;
    method: string;
    summary: string;
    description: string;
    /** array with or-relation, SecurityRequirementObject with and-relation */
    securities?: SecurityRequirementObject[];
    servers?: ServerObject[];
    params: Prisma.JsonObject;
    responses: Prisma.JsonObject;
    rawJson: Prisma.JsonObject;
  }[];
  securitySchemes?: { [name: string]: SecuritySchemeObject };
  servers?: ServerObject[];
  /** array with or-relation, SecurityRequirementObject with and-relation */
  securities?: SecurityRequirementObject[];
}
