-- AlterTable
ALTER TABLE "Callgent" ADD COLUMN     "avatar" VARCHAR(1023),
ADD COLUMN     "favorite" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "forked" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "liked" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "viewed" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "featured" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "official" BOOLEAN NOT NULL DEFAULT false;
