// @@generated by @pond918/prisma-generator-nestjs-dto@1.17.513. 2024-04-30
// modification to this file may be overwritten when regenerating.
import { ApiProperty } from '@nestjs/swagger';
import { IsBoolean, IsEmail, IsNotEmpty, IsOptional } from 'class-validator';

export class ValidationEmailVo {
  @ApiProperty({
    example: 'user@example.com',
    required: true,
    nullable: false,
  })
  @IsNotEmpty()
  @IsEmail()
  email: string;

  @ApiProperty({
    description: 'If true, a new user will be created if not exists.',
    required: false,
    nullable: true,
  })
  @IsOptional()
  @IsBoolean()
  create?: boolean;

  @ApiProperty({
    description:
      'If set to false, only validating email. Note: new user forces resetPwd.',
    required: false,
    nullable: true,
  })
  @IsOptional()
  @IsBoolean()
  resetPwd?: boolean;
}
