#!/bin/sh

# check 'Signed-off-by' in commit message
git_commit_message=$(cat "$1")
if [ -z "$(echo "$git_commit_message" | grep 'Signed-off-by: ')" ]; then
    echo
    echo "\033[31mError\033[0m:"
    echo "Commit message is missing the Signed-off-by line."
    echo "Please use 'git commit -s' to commit your changes."
    echo "You can add it manually with 'git commit --amend -s'."
    echo
    exit 1
fi

exit 0
